<?php
/**
 * OperateOperationsApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Aerospike REST Client
 *
 * REST Interface for Aerospike Database.
 *
 * OpenAPI spec version: 1.6.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Swagger\Client\ApiException;
use Swagger\Client\Configuration;
use Swagger\Client\HeaderSelector;
use Swagger\Client\ObjectSerializer;

/**
 * OperateOperationsApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OperateOperationsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation operateNamespaceKey
     *
     * Perform multiple operations atomically on the specified record.
     *
     * @param  \Swagger\Client\Model\Operation[] $body An array of operation objects specifying the operations to perform on the record (required)
     * @param  string $key Userkey for the record. (required)
     * @param  string $namespace Namespace for the record; equivalent to database name. (required)
     * @param  string $authorization Authorization (optional)
     * @param  string $commit_level Desired consistency guarantee when committing a transaction on the server. (optional, default to COMMIT_ALL)
     * @param  bool $compress Use zlib compression on command buffers sent to the server and responses received from the server when the buffer size is greater than 128 bytes. (optional, default to false)
     * @param  bool $durable_delete If the transaction results in a record deletion, leave a tombstone for the record. (optional, default to false)
     * @param  int $expiration Record expiration. Also known as ttl (time to live). Seconds record will live before being removed by the server. (optional)
     * @param  int $generation Expected generation. Generation is the number of times a record has been modified (including creation) on the server. (optional)
     * @param  string $generation_policy Qualify how to handle record writes based on record generation. (optional, default to NONE)
     * @param  string $keytype The Type of the userKey. (optional, default to STRING)
     * @param  int $max_retries Maximum number of retries before aborting the current transaction. The initial attempt is not counted as a retry. (optional)
     * @param  string $predexp Optional predicate expression filter in postfix notation. If the predicate expression exists and evaluates to false, the transaction is ignored. (optional, default to null)
     * @param  string $read_mode_ap Read policy for AP (availability) namespaces. How duplicates should be consulted in a read operation. Only makes a difference during migrations and only applicable in AP mode. (optional, default to ONE)
     * @param  string $read_mode_sc Read policy for SC (strong consistency) namespaces. Determines SC read consistency options. (optional, default to SESSION)
     * @param  string[] $record_bins Optionally specify a set of bins to return when fetching a record. If omitted, all bins will be returned. (optional)
     * @param  string $record_exists_action How to handle the existence of the record. This is ignored for POST/PUT/UPDATE kvs methods. (optional, default to UPDATE)
     * @param  string $replica Replica algorithm used to determine the target node for a single record command. (optional, default to SEQUENCE)
     * @param  bool $respond_all_ops For client operate(), return a result for every operation. (optional, default to false)
     * @param  bool $send_key Send user defined key in addition to hash digest on both reads and writes. (optional, default to false)
     * @param  int $sleep_between_retries Milliseconds to sleep between retries. (optional)
     * @param  int $socket_timeout Socket idle timeout in milliseconds when processing a database command. (optional)
     * @param  int $total_timeout Total transaction timeout in milliseconds. (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\Record
     */
    public function operateNamespaceKey($body, $key, $namespace, $authorization = null, $commit_level = 'COMMIT_ALL', $compress = 'false', $durable_delete = 'false', $expiration = null, $generation = null, $generation_policy = 'NONE', $keytype = 'STRING', $max_retries = null, $predexp = 'null', $read_mode_ap = 'ONE', $read_mode_sc = 'SESSION', $record_bins = null, $record_exists_action = 'UPDATE', $replica = 'SEQUENCE', $respond_all_ops = 'false', $send_key = 'false', $sleep_between_retries = null, $socket_timeout = null, $total_timeout = null)
    {
        list($response) = $this->operateNamespaceKeyWithHttpInfo($body, $key, $namespace, $authorization, $commit_level, $compress, $durable_delete, $expiration, $generation, $generation_policy, $keytype, $max_retries, $predexp, $read_mode_ap, $read_mode_sc, $record_bins, $record_exists_action, $replica, $respond_all_ops, $send_key, $sleep_between_retries, $socket_timeout, $total_timeout);
        return $response;
    }

    /**
     * Operation operateNamespaceKeyWithHttpInfo
     *
     * Perform multiple operations atomically on the specified record.
     *
     * @param  \Swagger\Client\Model\Operation[] $body An array of operation objects specifying the operations to perform on the record (required)
     * @param  string $key Userkey for the record. (required)
     * @param  string $namespace Namespace for the record; equivalent to database name. (required)
     * @param  string $authorization Authorization (optional)
     * @param  string $commit_level Desired consistency guarantee when committing a transaction on the server. (optional, default to COMMIT_ALL)
     * @param  bool $compress Use zlib compression on command buffers sent to the server and responses received from the server when the buffer size is greater than 128 bytes. (optional, default to false)
     * @param  bool $durable_delete If the transaction results in a record deletion, leave a tombstone for the record. (optional, default to false)
     * @param  int $expiration Record expiration. Also known as ttl (time to live). Seconds record will live before being removed by the server. (optional)
     * @param  int $generation Expected generation. Generation is the number of times a record has been modified (including creation) on the server. (optional)
     * @param  string $generation_policy Qualify how to handle record writes based on record generation. (optional, default to NONE)
     * @param  string $keytype The Type of the userKey. (optional, default to STRING)
     * @param  int $max_retries Maximum number of retries before aborting the current transaction. The initial attempt is not counted as a retry. (optional)
     * @param  string $predexp Optional predicate expression filter in postfix notation. If the predicate expression exists and evaluates to false, the transaction is ignored. (optional, default to null)
     * @param  string $read_mode_ap Read policy for AP (availability) namespaces. How duplicates should be consulted in a read operation. Only makes a difference during migrations and only applicable in AP mode. (optional, default to ONE)
     * @param  string $read_mode_sc Read policy for SC (strong consistency) namespaces. Determines SC read consistency options. (optional, default to SESSION)
     * @param  string[] $record_bins Optionally specify a set of bins to return when fetching a record. If omitted, all bins will be returned. (optional)
     * @param  string $record_exists_action How to handle the existence of the record. This is ignored for POST/PUT/UPDATE kvs methods. (optional, default to UPDATE)
     * @param  string $replica Replica algorithm used to determine the target node for a single record command. (optional, default to SEQUENCE)
     * @param  bool $respond_all_ops For client operate(), return a result for every operation. (optional, default to false)
     * @param  bool $send_key Send user defined key in addition to hash digest on both reads and writes. (optional, default to false)
     * @param  int $sleep_between_retries Milliseconds to sleep between retries. (optional)
     * @param  int $socket_timeout Socket idle timeout in milliseconds when processing a database command. (optional)
     * @param  int $total_timeout Total transaction timeout in milliseconds. (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\Record, HTTP status code, HTTP response headers (array of strings)
     */
    public function operateNamespaceKeyWithHttpInfo($body, $key, $namespace, $authorization = null, $commit_level = 'COMMIT_ALL', $compress = 'false', $durable_delete = 'false', $expiration = null, $generation = null, $generation_policy = 'NONE', $keytype = 'STRING', $max_retries = null, $predexp = 'null', $read_mode_ap = 'ONE', $read_mode_sc = 'SESSION', $record_bins = null, $record_exists_action = 'UPDATE', $replica = 'SEQUENCE', $respond_all_ops = 'false', $send_key = 'false', $sleep_between_retries = null, $socket_timeout = null, $total_timeout = null)
    {
        $returnType = '\Swagger\Client\Model\Record';
        $request = $this->operateNamespaceKeyRequest($body, $key, $namespace, $authorization, $commit_level, $compress, $durable_delete, $expiration, $generation, $generation_policy, $keytype, $max_retries, $predexp, $read_mode_ap, $read_mode_sc, $record_bins, $record_exists_action, $replica, $respond_all_ops, $send_key, $sleep_between_retries, $socket_timeout, $total_timeout);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Record',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\RestClientError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\RestClientError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\RestClientError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\RestClientError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\RestClientError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation operateNamespaceKeyAsync
     *
     * Perform multiple operations atomically on the specified record.
     *
     * @param  \Swagger\Client\Model\Operation[] $body An array of operation objects specifying the operations to perform on the record (required)
     * @param  string $key Userkey for the record. (required)
     * @param  string $namespace Namespace for the record; equivalent to database name. (required)
     * @param  string $authorization Authorization (optional)
     * @param  string $commit_level Desired consistency guarantee when committing a transaction on the server. (optional, default to COMMIT_ALL)
     * @param  bool $compress Use zlib compression on command buffers sent to the server and responses received from the server when the buffer size is greater than 128 bytes. (optional, default to false)
     * @param  bool $durable_delete If the transaction results in a record deletion, leave a tombstone for the record. (optional, default to false)
     * @param  int $expiration Record expiration. Also known as ttl (time to live). Seconds record will live before being removed by the server. (optional)
     * @param  int $generation Expected generation. Generation is the number of times a record has been modified (including creation) on the server. (optional)
     * @param  string $generation_policy Qualify how to handle record writes based on record generation. (optional, default to NONE)
     * @param  string $keytype The Type of the userKey. (optional, default to STRING)
     * @param  int $max_retries Maximum number of retries before aborting the current transaction. The initial attempt is not counted as a retry. (optional)
     * @param  string $predexp Optional predicate expression filter in postfix notation. If the predicate expression exists and evaluates to false, the transaction is ignored. (optional, default to null)
     * @param  string $read_mode_ap Read policy for AP (availability) namespaces. How duplicates should be consulted in a read operation. Only makes a difference during migrations and only applicable in AP mode. (optional, default to ONE)
     * @param  string $read_mode_sc Read policy for SC (strong consistency) namespaces. Determines SC read consistency options. (optional, default to SESSION)
     * @param  string[] $record_bins Optionally specify a set of bins to return when fetching a record. If omitted, all bins will be returned. (optional)
     * @param  string $record_exists_action How to handle the existence of the record. This is ignored for POST/PUT/UPDATE kvs methods. (optional, default to UPDATE)
     * @param  string $replica Replica algorithm used to determine the target node for a single record command. (optional, default to SEQUENCE)
     * @param  bool $respond_all_ops For client operate(), return a result for every operation. (optional, default to false)
     * @param  bool $send_key Send user defined key in addition to hash digest on both reads and writes. (optional, default to false)
     * @param  int $sleep_between_retries Milliseconds to sleep between retries. (optional)
     * @param  int $socket_timeout Socket idle timeout in milliseconds when processing a database command. (optional)
     * @param  int $total_timeout Total transaction timeout in milliseconds. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function operateNamespaceKeyAsync($body, $key, $namespace, $authorization = null, $commit_level = 'COMMIT_ALL', $compress = 'false', $durable_delete = 'false', $expiration = null, $generation = null, $generation_policy = 'NONE', $keytype = 'STRING', $max_retries = null, $predexp = 'null', $read_mode_ap = 'ONE', $read_mode_sc = 'SESSION', $record_bins = null, $record_exists_action = 'UPDATE', $replica = 'SEQUENCE', $respond_all_ops = 'false', $send_key = 'false', $sleep_between_retries = null, $socket_timeout = null, $total_timeout = null)
    {
        return $this->operateNamespaceKeyAsyncWithHttpInfo($body, $key, $namespace, $authorization, $commit_level, $compress, $durable_delete, $expiration, $generation, $generation_policy, $keytype, $max_retries, $predexp, $read_mode_ap, $read_mode_sc, $record_bins, $record_exists_action, $replica, $respond_all_ops, $send_key, $sleep_between_retries, $socket_timeout, $total_timeout)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation operateNamespaceKeyAsyncWithHttpInfo
     *
     * Perform multiple operations atomically on the specified record.
     *
     * @param  \Swagger\Client\Model\Operation[] $body An array of operation objects specifying the operations to perform on the record (required)
     * @param  string $key Userkey for the record. (required)
     * @param  string $namespace Namespace for the record; equivalent to database name. (required)
     * @param  string $authorization Authorization (optional)
     * @param  string $commit_level Desired consistency guarantee when committing a transaction on the server. (optional, default to COMMIT_ALL)
     * @param  bool $compress Use zlib compression on command buffers sent to the server and responses received from the server when the buffer size is greater than 128 bytes. (optional, default to false)
     * @param  bool $durable_delete If the transaction results in a record deletion, leave a tombstone for the record. (optional, default to false)
     * @param  int $expiration Record expiration. Also known as ttl (time to live). Seconds record will live before being removed by the server. (optional)
     * @param  int $generation Expected generation. Generation is the number of times a record has been modified (including creation) on the server. (optional)
     * @param  string $generation_policy Qualify how to handle record writes based on record generation. (optional, default to NONE)
     * @param  string $keytype The Type of the userKey. (optional, default to STRING)
     * @param  int $max_retries Maximum number of retries before aborting the current transaction. The initial attempt is not counted as a retry. (optional)
     * @param  string $predexp Optional predicate expression filter in postfix notation. If the predicate expression exists and evaluates to false, the transaction is ignored. (optional, default to null)
     * @param  string $read_mode_ap Read policy for AP (availability) namespaces. How duplicates should be consulted in a read operation. Only makes a difference during migrations and only applicable in AP mode. (optional, default to ONE)
     * @param  string $read_mode_sc Read policy for SC (strong consistency) namespaces. Determines SC read consistency options. (optional, default to SESSION)
     * @param  string[] $record_bins Optionally specify a set of bins to return when fetching a record. If omitted, all bins will be returned. (optional)
     * @param  string $record_exists_action How to handle the existence of the record. This is ignored for POST/PUT/UPDATE kvs methods. (optional, default to UPDATE)
     * @param  string $replica Replica algorithm used to determine the target node for a single record command. (optional, default to SEQUENCE)
     * @param  bool $respond_all_ops For client operate(), return a result for every operation. (optional, default to false)
     * @param  bool $send_key Send user defined key in addition to hash digest on both reads and writes. (optional, default to false)
     * @param  int $sleep_between_retries Milliseconds to sleep between retries. (optional)
     * @param  int $socket_timeout Socket idle timeout in milliseconds when processing a database command. (optional)
     * @param  int $total_timeout Total transaction timeout in milliseconds. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function operateNamespaceKeyAsyncWithHttpInfo($body, $key, $namespace, $authorization = null, $commit_level = 'COMMIT_ALL', $compress = 'false', $durable_delete = 'false', $expiration = null, $generation = null, $generation_policy = 'NONE', $keytype = 'STRING', $max_retries = null, $predexp = 'null', $read_mode_ap = 'ONE', $read_mode_sc = 'SESSION', $record_bins = null, $record_exists_action = 'UPDATE', $replica = 'SEQUENCE', $respond_all_ops = 'false', $send_key = 'false', $sleep_between_retries = null, $socket_timeout = null, $total_timeout = null)
    {
        $returnType = '\Swagger\Client\Model\Record';
        $request = $this->operateNamespaceKeyRequest($body, $key, $namespace, $authorization, $commit_level, $compress, $durable_delete, $expiration, $generation, $generation_policy, $keytype, $max_retries, $predexp, $read_mode_ap, $read_mode_sc, $record_bins, $record_exists_action, $replica, $respond_all_ops, $send_key, $sleep_between_retries, $socket_timeout, $total_timeout);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'operateNamespaceKey'
     *
     * @param  \Swagger\Client\Model\Operation[] $body An array of operation objects specifying the operations to perform on the record (required)
     * @param  string $key Userkey for the record. (required)
     * @param  string $namespace Namespace for the record; equivalent to database name. (required)
     * @param  string $authorization Authorization (optional)
     * @param  string $commit_level Desired consistency guarantee when committing a transaction on the server. (optional, default to COMMIT_ALL)
     * @param  bool $compress Use zlib compression on command buffers sent to the server and responses received from the server when the buffer size is greater than 128 bytes. (optional, default to false)
     * @param  bool $durable_delete If the transaction results in a record deletion, leave a tombstone for the record. (optional, default to false)
     * @param  int $expiration Record expiration. Also known as ttl (time to live). Seconds record will live before being removed by the server. (optional)
     * @param  int $generation Expected generation. Generation is the number of times a record has been modified (including creation) on the server. (optional)
     * @param  string $generation_policy Qualify how to handle record writes based on record generation. (optional, default to NONE)
     * @param  string $keytype The Type of the userKey. (optional, default to STRING)
     * @param  int $max_retries Maximum number of retries before aborting the current transaction. The initial attempt is not counted as a retry. (optional)
     * @param  string $predexp Optional predicate expression filter in postfix notation. If the predicate expression exists and evaluates to false, the transaction is ignored. (optional, default to null)
     * @param  string $read_mode_ap Read policy for AP (availability) namespaces. How duplicates should be consulted in a read operation. Only makes a difference during migrations and only applicable in AP mode. (optional, default to ONE)
     * @param  string $read_mode_sc Read policy for SC (strong consistency) namespaces. Determines SC read consistency options. (optional, default to SESSION)
     * @param  string[] $record_bins Optionally specify a set of bins to return when fetching a record. If omitted, all bins will be returned. (optional)
     * @param  string $record_exists_action How to handle the existence of the record. This is ignored for POST/PUT/UPDATE kvs methods. (optional, default to UPDATE)
     * @param  string $replica Replica algorithm used to determine the target node for a single record command. (optional, default to SEQUENCE)
     * @param  bool $respond_all_ops For client operate(), return a result for every operation. (optional, default to false)
     * @param  bool $send_key Send user defined key in addition to hash digest on both reads and writes. (optional, default to false)
     * @param  int $sleep_between_retries Milliseconds to sleep between retries. (optional)
     * @param  int $socket_timeout Socket idle timeout in milliseconds when processing a database command. (optional)
     * @param  int $total_timeout Total transaction timeout in milliseconds. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function operateNamespaceKeyRequest($body, $key, $namespace, $authorization = null, $commit_level = 'COMMIT_ALL', $compress = 'false', $durable_delete = 'false', $expiration = null, $generation = null, $generation_policy = 'NONE', $keytype = 'STRING', $max_retries = null, $predexp = 'null', $read_mode_ap = 'ONE', $read_mode_sc = 'SESSION', $record_bins = null, $record_exists_action = 'UPDATE', $replica = 'SEQUENCE', $respond_all_ops = 'false', $send_key = 'false', $sleep_between_retries = null, $socket_timeout = null, $total_timeout = null)
    {
        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling operateNamespaceKey'
            );
        }
        // verify the required parameter 'key' is set
        if ($key === null || (is_array($key) && count($key) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $key when calling operateNamespaceKey'
            );
        }
        // verify the required parameter 'namespace' is set
        if ($namespace === null || (is_array($namespace) && count($namespace) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $namespace when calling operateNamespaceKey'
            );
        }

        $resourcePath = '/v1/operate/{namespace}/{key}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($commit_level !== null) {
            $queryParams['commitLevel'] = ObjectSerializer::toQueryValue($commit_level, null);
        }
        // query params
        if ($compress !== null) {
            $queryParams['compress'] = ObjectSerializer::toQueryValue($compress, null);
        }
        // query params
        if ($durable_delete !== null) {
            $queryParams['durableDelete'] = ObjectSerializer::toQueryValue($durable_delete, null);
        }
        // query params
        if ($expiration !== null) {
            $queryParams['expiration'] = ObjectSerializer::toQueryValue($expiration, 'int32');
        }
        // query params
        if ($generation !== null) {
            $queryParams['generation'] = ObjectSerializer::toQueryValue($generation, 'int32');
        }
        // query params
        if ($generation_policy !== null) {
            $queryParams['generationPolicy'] = ObjectSerializer::toQueryValue($generation_policy, null);
        }
        // query params
        if ($keytype !== null) {
            $queryParams['keytype'] = ObjectSerializer::toQueryValue($keytype, null);
        }
        // query params
        if ($max_retries !== null) {
            $queryParams['maxRetries'] = ObjectSerializer::toQueryValue($max_retries, 'int32');
        }
        // query params
        if ($predexp !== null) {
            $queryParams['predexp'] = ObjectSerializer::toQueryValue($predexp, null);
        }
        // query params
        if ($read_mode_ap !== null) {
            $queryParams['readModeAP'] = ObjectSerializer::toQueryValue($read_mode_ap, null);
        }
        // query params
        if ($read_mode_sc !== null) {
            $queryParams['readModeSC'] = ObjectSerializer::toQueryValue($read_mode_sc, null);
        }
        // query params
        if (is_array($record_bins)) {
            $record_bins = ObjectSerializer::serializeCollection($record_bins, 'multi', true);
        }
        if ($record_bins !== null) {
            $queryParams['recordBins'] = ObjectSerializer::toQueryValue($record_bins, null);
        }
        // query params
        if ($record_exists_action !== null) {
            $queryParams['recordExistsAction'] = ObjectSerializer::toQueryValue($record_exists_action, null);
        }
        // query params
        if ($replica !== null) {
            $queryParams['replica'] = ObjectSerializer::toQueryValue($replica, null);
        }
        // query params
        if ($respond_all_ops !== null) {
            $queryParams['respondAllOps'] = ObjectSerializer::toQueryValue($respond_all_ops, null);
        }
        // query params
        if ($send_key !== null) {
            $queryParams['sendKey'] = ObjectSerializer::toQueryValue($send_key, null);
        }
        // query params
        if ($sleep_between_retries !== null) {
            $queryParams['sleepBetweenRetries'] = ObjectSerializer::toQueryValue($sleep_between_retries, 'int32');
        }
        // query params
        if ($socket_timeout !== null) {
            $queryParams['socketTimeout'] = ObjectSerializer::toQueryValue($socket_timeout, 'int32');
        }
        // query params
        if ($total_timeout !== null) {
            $queryParams['totalTimeout'] = ObjectSerializer::toQueryValue($total_timeout, 'int32');
        }
        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }

        // path params
        if ($key !== null) {
            $resourcePath = str_replace(
                '{' . 'key' . '}',
                ObjectSerializer::toPathValue($key),
                $resourcePath
            );
        }
        // path params
        if ($namespace !== null) {
            $resourcePath = str_replace(
                '{' . 'namespace' . '}',
                ObjectSerializer::toPathValue($namespace),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'application/msgpack']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'application/msgpack'],
                ['application/json', 'application/msgpack']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation operateNamespaceSetKey
     *
     * Perform multiple operations atomically on the specified record.
     *
     * @param  \Swagger\Client\Model\Operation[] $body An array of operation objects specifying the operations to perform on the record (required)
     * @param  string $key Userkey for the record. (required)
     * @param  string $namespace Namespace for the record; equivalent to database name. (required)
     * @param  string $set Set for the record; equivalent to database table. (required)
     * @param  string $authorization Authorization (optional)
     * @param  string $commit_level Desired consistency guarantee when committing a transaction on the server. (optional, default to COMMIT_ALL)
     * @param  bool $compress Use zlib compression on command buffers sent to the server and responses received from the server when the buffer size is greater than 128 bytes. (optional, default to false)
     * @param  bool $durable_delete If the transaction results in a record deletion, leave a tombstone for the record. (optional, default to false)
     * @param  int $expiration Record expiration. Also known as ttl (time to live). Seconds record will live before being removed by the server. (optional)
     * @param  int $generation Expected generation. Generation is the number of times a record has been modified (including creation) on the server. (optional)
     * @param  string $generation_policy Qualify how to handle record writes based on record generation. (optional, default to NONE)
     * @param  string $keytype The Type of the userKey. (optional, default to STRING)
     * @param  int $max_retries Maximum number of retries before aborting the current transaction. The initial attempt is not counted as a retry. (optional)
     * @param  string $predexp Optional predicate expression filter in postfix notation. If the predicate expression exists and evaluates to false, the transaction is ignored. (optional, default to null)
     * @param  string $read_mode_ap Read policy for AP (availability) namespaces. How duplicates should be consulted in a read operation. Only makes a difference during migrations and only applicable in AP mode. (optional, default to ONE)
     * @param  string $read_mode_sc Read policy for SC (strong consistency) namespaces. Determines SC read consistency options. (optional, default to SESSION)
     * @param  string[] $record_bins Optionally specify a set of bins to return when fetching a record. If omitted, all bins will be returned. (optional)
     * @param  string $record_exists_action How to handle the existence of the record. This is ignored for POST/PUT/UPDATE kvs methods. (optional, default to UPDATE)
     * @param  string $replica Replica algorithm used to determine the target node for a single record command. (optional, default to SEQUENCE)
     * @param  bool $respond_all_ops For client operate(), return a result for every operation. (optional, default to false)
     * @param  bool $send_key Send user defined key in addition to hash digest on both reads and writes. (optional, default to false)
     * @param  int $sleep_between_retries Milliseconds to sleep between retries. (optional)
     * @param  int $socket_timeout Socket idle timeout in milliseconds when processing a database command. (optional)
     * @param  int $total_timeout Total transaction timeout in milliseconds. (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\Record
     */
    public function operateNamespaceSetKey($body, $key, $namespace, $set, $authorization = null, $commit_level = 'COMMIT_ALL', $compress = 'false', $durable_delete = 'false', $expiration = null, $generation = null, $generation_policy = 'NONE', $keytype = 'STRING', $max_retries = null, $predexp = 'null', $read_mode_ap = 'ONE', $read_mode_sc = 'SESSION', $record_bins = null, $record_exists_action = 'UPDATE', $replica = 'SEQUENCE', $respond_all_ops = 'false', $send_key = 'false', $sleep_between_retries = null, $socket_timeout = null, $total_timeout = null)
    {
        list($response) = $this->operateNamespaceSetKeyWithHttpInfo($body, $key, $namespace, $set, $authorization, $commit_level, $compress, $durable_delete, $expiration, $generation, $generation_policy, $keytype, $max_retries, $predexp, $read_mode_ap, $read_mode_sc, $record_bins, $record_exists_action, $replica, $respond_all_ops, $send_key, $sleep_between_retries, $socket_timeout, $total_timeout);
        return $response;
    }

    /**
     * Operation operateNamespaceSetKeyWithHttpInfo
     *
     * Perform multiple operations atomically on the specified record.
     *
     * @param  \Swagger\Client\Model\Operation[] $body An array of operation objects specifying the operations to perform on the record (required)
     * @param  string $key Userkey for the record. (required)
     * @param  string $namespace Namespace for the record; equivalent to database name. (required)
     * @param  string $set Set for the record; equivalent to database table. (required)
     * @param  string $authorization Authorization (optional)
     * @param  string $commit_level Desired consistency guarantee when committing a transaction on the server. (optional, default to COMMIT_ALL)
     * @param  bool $compress Use zlib compression on command buffers sent to the server and responses received from the server when the buffer size is greater than 128 bytes. (optional, default to false)
     * @param  bool $durable_delete If the transaction results in a record deletion, leave a tombstone for the record. (optional, default to false)
     * @param  int $expiration Record expiration. Also known as ttl (time to live). Seconds record will live before being removed by the server. (optional)
     * @param  int $generation Expected generation. Generation is the number of times a record has been modified (including creation) on the server. (optional)
     * @param  string $generation_policy Qualify how to handle record writes based on record generation. (optional, default to NONE)
     * @param  string $keytype The Type of the userKey. (optional, default to STRING)
     * @param  int $max_retries Maximum number of retries before aborting the current transaction. The initial attempt is not counted as a retry. (optional)
     * @param  string $predexp Optional predicate expression filter in postfix notation. If the predicate expression exists and evaluates to false, the transaction is ignored. (optional, default to null)
     * @param  string $read_mode_ap Read policy for AP (availability) namespaces. How duplicates should be consulted in a read operation. Only makes a difference during migrations and only applicable in AP mode. (optional, default to ONE)
     * @param  string $read_mode_sc Read policy for SC (strong consistency) namespaces. Determines SC read consistency options. (optional, default to SESSION)
     * @param  string[] $record_bins Optionally specify a set of bins to return when fetching a record. If omitted, all bins will be returned. (optional)
     * @param  string $record_exists_action How to handle the existence of the record. This is ignored for POST/PUT/UPDATE kvs methods. (optional, default to UPDATE)
     * @param  string $replica Replica algorithm used to determine the target node for a single record command. (optional, default to SEQUENCE)
     * @param  bool $respond_all_ops For client operate(), return a result for every operation. (optional, default to false)
     * @param  bool $send_key Send user defined key in addition to hash digest on both reads and writes. (optional, default to false)
     * @param  int $sleep_between_retries Milliseconds to sleep between retries. (optional)
     * @param  int $socket_timeout Socket idle timeout in milliseconds when processing a database command. (optional)
     * @param  int $total_timeout Total transaction timeout in milliseconds. (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\Record, HTTP status code, HTTP response headers (array of strings)
     */
    public function operateNamespaceSetKeyWithHttpInfo($body, $key, $namespace, $set, $authorization = null, $commit_level = 'COMMIT_ALL', $compress = 'false', $durable_delete = 'false', $expiration = null, $generation = null, $generation_policy = 'NONE', $keytype = 'STRING', $max_retries = null, $predexp = 'null', $read_mode_ap = 'ONE', $read_mode_sc = 'SESSION', $record_bins = null, $record_exists_action = 'UPDATE', $replica = 'SEQUENCE', $respond_all_ops = 'false', $send_key = 'false', $sleep_between_retries = null, $socket_timeout = null, $total_timeout = null)
    {
        $returnType = '\Swagger\Client\Model\Record';
        $request = $this->operateNamespaceSetKeyRequest($body, $key, $namespace, $set, $authorization, $commit_level, $compress, $durable_delete, $expiration, $generation, $generation_policy, $keytype, $max_retries, $predexp, $read_mode_ap, $read_mode_sc, $record_bins, $record_exists_action, $replica, $respond_all_ops, $send_key, $sleep_between_retries, $socket_timeout, $total_timeout);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Record',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\RestClientError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\RestClientError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\RestClientError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\RestClientError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\RestClientError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation operateNamespaceSetKeyAsync
     *
     * Perform multiple operations atomically on the specified record.
     *
     * @param  \Swagger\Client\Model\Operation[] $body An array of operation objects specifying the operations to perform on the record (required)
     * @param  string $key Userkey for the record. (required)
     * @param  string $namespace Namespace for the record; equivalent to database name. (required)
     * @param  string $set Set for the record; equivalent to database table. (required)
     * @param  string $authorization Authorization (optional)
     * @param  string $commit_level Desired consistency guarantee when committing a transaction on the server. (optional, default to COMMIT_ALL)
     * @param  bool $compress Use zlib compression on command buffers sent to the server and responses received from the server when the buffer size is greater than 128 bytes. (optional, default to false)
     * @param  bool $durable_delete If the transaction results in a record deletion, leave a tombstone for the record. (optional, default to false)
     * @param  int $expiration Record expiration. Also known as ttl (time to live). Seconds record will live before being removed by the server. (optional)
     * @param  int $generation Expected generation. Generation is the number of times a record has been modified (including creation) on the server. (optional)
     * @param  string $generation_policy Qualify how to handle record writes based on record generation. (optional, default to NONE)
     * @param  string $keytype The Type of the userKey. (optional, default to STRING)
     * @param  int $max_retries Maximum number of retries before aborting the current transaction. The initial attempt is not counted as a retry. (optional)
     * @param  string $predexp Optional predicate expression filter in postfix notation. If the predicate expression exists and evaluates to false, the transaction is ignored. (optional, default to null)
     * @param  string $read_mode_ap Read policy for AP (availability) namespaces. How duplicates should be consulted in a read operation. Only makes a difference during migrations and only applicable in AP mode. (optional, default to ONE)
     * @param  string $read_mode_sc Read policy for SC (strong consistency) namespaces. Determines SC read consistency options. (optional, default to SESSION)
     * @param  string[] $record_bins Optionally specify a set of bins to return when fetching a record. If omitted, all bins will be returned. (optional)
     * @param  string $record_exists_action How to handle the existence of the record. This is ignored for POST/PUT/UPDATE kvs methods. (optional, default to UPDATE)
     * @param  string $replica Replica algorithm used to determine the target node for a single record command. (optional, default to SEQUENCE)
     * @param  bool $respond_all_ops For client operate(), return a result for every operation. (optional, default to false)
     * @param  bool $send_key Send user defined key in addition to hash digest on both reads and writes. (optional, default to false)
     * @param  int $sleep_between_retries Milliseconds to sleep between retries. (optional)
     * @param  int $socket_timeout Socket idle timeout in milliseconds when processing a database command. (optional)
     * @param  int $total_timeout Total transaction timeout in milliseconds. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function operateNamespaceSetKeyAsync($body, $key, $namespace, $set, $authorization = null, $commit_level = 'COMMIT_ALL', $compress = 'false', $durable_delete = 'false', $expiration = null, $generation = null, $generation_policy = 'NONE', $keytype = 'STRING', $max_retries = null, $predexp = 'null', $read_mode_ap = 'ONE', $read_mode_sc = 'SESSION', $record_bins = null, $record_exists_action = 'UPDATE', $replica = 'SEQUENCE', $respond_all_ops = 'false', $send_key = 'false', $sleep_between_retries = null, $socket_timeout = null, $total_timeout = null)
    {
        return $this->operateNamespaceSetKeyAsyncWithHttpInfo($body, $key, $namespace, $set, $authorization, $commit_level, $compress, $durable_delete, $expiration, $generation, $generation_policy, $keytype, $max_retries, $predexp, $read_mode_ap, $read_mode_sc, $record_bins, $record_exists_action, $replica, $respond_all_ops, $send_key, $sleep_between_retries, $socket_timeout, $total_timeout)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation operateNamespaceSetKeyAsyncWithHttpInfo
     *
     * Perform multiple operations atomically on the specified record.
     *
     * @param  \Swagger\Client\Model\Operation[] $body An array of operation objects specifying the operations to perform on the record (required)
     * @param  string $key Userkey for the record. (required)
     * @param  string $namespace Namespace for the record; equivalent to database name. (required)
     * @param  string $set Set for the record; equivalent to database table. (required)
     * @param  string $authorization Authorization (optional)
     * @param  string $commit_level Desired consistency guarantee when committing a transaction on the server. (optional, default to COMMIT_ALL)
     * @param  bool $compress Use zlib compression on command buffers sent to the server and responses received from the server when the buffer size is greater than 128 bytes. (optional, default to false)
     * @param  bool $durable_delete If the transaction results in a record deletion, leave a tombstone for the record. (optional, default to false)
     * @param  int $expiration Record expiration. Also known as ttl (time to live). Seconds record will live before being removed by the server. (optional)
     * @param  int $generation Expected generation. Generation is the number of times a record has been modified (including creation) on the server. (optional)
     * @param  string $generation_policy Qualify how to handle record writes based on record generation. (optional, default to NONE)
     * @param  string $keytype The Type of the userKey. (optional, default to STRING)
     * @param  int $max_retries Maximum number of retries before aborting the current transaction. The initial attempt is not counted as a retry. (optional)
     * @param  string $predexp Optional predicate expression filter in postfix notation. If the predicate expression exists and evaluates to false, the transaction is ignored. (optional, default to null)
     * @param  string $read_mode_ap Read policy for AP (availability) namespaces. How duplicates should be consulted in a read operation. Only makes a difference during migrations and only applicable in AP mode. (optional, default to ONE)
     * @param  string $read_mode_sc Read policy for SC (strong consistency) namespaces. Determines SC read consistency options. (optional, default to SESSION)
     * @param  string[] $record_bins Optionally specify a set of bins to return when fetching a record. If omitted, all bins will be returned. (optional)
     * @param  string $record_exists_action How to handle the existence of the record. This is ignored for POST/PUT/UPDATE kvs methods. (optional, default to UPDATE)
     * @param  string $replica Replica algorithm used to determine the target node for a single record command. (optional, default to SEQUENCE)
     * @param  bool $respond_all_ops For client operate(), return a result for every operation. (optional, default to false)
     * @param  bool $send_key Send user defined key in addition to hash digest on both reads and writes. (optional, default to false)
     * @param  int $sleep_between_retries Milliseconds to sleep between retries. (optional)
     * @param  int $socket_timeout Socket idle timeout in milliseconds when processing a database command. (optional)
     * @param  int $total_timeout Total transaction timeout in milliseconds. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function operateNamespaceSetKeyAsyncWithHttpInfo($body, $key, $namespace, $set, $authorization = null, $commit_level = 'COMMIT_ALL', $compress = 'false', $durable_delete = 'false', $expiration = null, $generation = null, $generation_policy = 'NONE', $keytype = 'STRING', $max_retries = null, $predexp = 'null', $read_mode_ap = 'ONE', $read_mode_sc = 'SESSION', $record_bins = null, $record_exists_action = 'UPDATE', $replica = 'SEQUENCE', $respond_all_ops = 'false', $send_key = 'false', $sleep_between_retries = null, $socket_timeout = null, $total_timeout = null)
    {
        $returnType = '\Swagger\Client\Model\Record';
        $request = $this->operateNamespaceSetKeyRequest($body, $key, $namespace, $set, $authorization, $commit_level, $compress, $durable_delete, $expiration, $generation, $generation_policy, $keytype, $max_retries, $predexp, $read_mode_ap, $read_mode_sc, $record_bins, $record_exists_action, $replica, $respond_all_ops, $send_key, $sleep_between_retries, $socket_timeout, $total_timeout);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'operateNamespaceSetKey'
     *
     * @param  \Swagger\Client\Model\Operation[] $body An array of operation objects specifying the operations to perform on the record (required)
     * @param  string $key Userkey for the record. (required)
     * @param  string $namespace Namespace for the record; equivalent to database name. (required)
     * @param  string $set Set for the record; equivalent to database table. (required)
     * @param  string $authorization Authorization (optional)
     * @param  string $commit_level Desired consistency guarantee when committing a transaction on the server. (optional, default to COMMIT_ALL)
     * @param  bool $compress Use zlib compression on command buffers sent to the server and responses received from the server when the buffer size is greater than 128 bytes. (optional, default to false)
     * @param  bool $durable_delete If the transaction results in a record deletion, leave a tombstone for the record. (optional, default to false)
     * @param  int $expiration Record expiration. Also known as ttl (time to live). Seconds record will live before being removed by the server. (optional)
     * @param  int $generation Expected generation. Generation is the number of times a record has been modified (including creation) on the server. (optional)
     * @param  string $generation_policy Qualify how to handle record writes based on record generation. (optional, default to NONE)
     * @param  string $keytype The Type of the userKey. (optional, default to STRING)
     * @param  int $max_retries Maximum number of retries before aborting the current transaction. The initial attempt is not counted as a retry. (optional)
     * @param  string $predexp Optional predicate expression filter in postfix notation. If the predicate expression exists and evaluates to false, the transaction is ignored. (optional, default to null)
     * @param  string $read_mode_ap Read policy for AP (availability) namespaces. How duplicates should be consulted in a read operation. Only makes a difference during migrations and only applicable in AP mode. (optional, default to ONE)
     * @param  string $read_mode_sc Read policy for SC (strong consistency) namespaces. Determines SC read consistency options. (optional, default to SESSION)
     * @param  string[] $record_bins Optionally specify a set of bins to return when fetching a record. If omitted, all bins will be returned. (optional)
     * @param  string $record_exists_action How to handle the existence of the record. This is ignored for POST/PUT/UPDATE kvs methods. (optional, default to UPDATE)
     * @param  string $replica Replica algorithm used to determine the target node for a single record command. (optional, default to SEQUENCE)
     * @param  bool $respond_all_ops For client operate(), return a result for every operation. (optional, default to false)
     * @param  bool $send_key Send user defined key in addition to hash digest on both reads and writes. (optional, default to false)
     * @param  int $sleep_between_retries Milliseconds to sleep between retries. (optional)
     * @param  int $socket_timeout Socket idle timeout in milliseconds when processing a database command. (optional)
     * @param  int $total_timeout Total transaction timeout in milliseconds. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function operateNamespaceSetKeyRequest($body, $key, $namespace, $set, $authorization = null, $commit_level = 'COMMIT_ALL', $compress = 'false', $durable_delete = 'false', $expiration = null, $generation = null, $generation_policy = 'NONE', $keytype = 'STRING', $max_retries = null, $predexp = 'null', $read_mode_ap = 'ONE', $read_mode_sc = 'SESSION', $record_bins = null, $record_exists_action = 'UPDATE', $replica = 'SEQUENCE', $respond_all_ops = 'false', $send_key = 'false', $sleep_between_retries = null, $socket_timeout = null, $total_timeout = null)
    {
        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling operateNamespaceSetKey'
            );
        }
        // verify the required parameter 'key' is set
        if ($key === null || (is_array($key) && count($key) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $key when calling operateNamespaceSetKey'
            );
        }
        // verify the required parameter 'namespace' is set
        if ($namespace === null || (is_array($namespace) && count($namespace) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $namespace when calling operateNamespaceSetKey'
            );
        }
        // verify the required parameter 'set' is set
        if ($set === null || (is_array($set) && count($set) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $set when calling operateNamespaceSetKey'
            );
        }

        $resourcePath = '/v1/operate/{namespace}/{set}/{key}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($commit_level !== null) {
            $queryParams['commitLevel'] = ObjectSerializer::toQueryValue($commit_level, null);
        }
        // query params
        if ($compress !== null) {
            $queryParams['compress'] = ObjectSerializer::toQueryValue($compress, null);
        }
        // query params
        if ($durable_delete !== null) {
            $queryParams['durableDelete'] = ObjectSerializer::toQueryValue($durable_delete, null);
        }
        // query params
        if ($expiration !== null) {
            $queryParams['expiration'] = ObjectSerializer::toQueryValue($expiration, 'int32');
        }
        // query params
        if ($generation !== null) {
            $queryParams['generation'] = ObjectSerializer::toQueryValue($generation, 'int32');
        }
        // query params
        if ($generation_policy !== null) {
            $queryParams['generationPolicy'] = ObjectSerializer::toQueryValue($generation_policy, null);
        }
        // query params
        if ($keytype !== null) {
            $queryParams['keytype'] = ObjectSerializer::toQueryValue($keytype, null);
        }
        // query params
        if ($max_retries !== null) {
            $queryParams['maxRetries'] = ObjectSerializer::toQueryValue($max_retries, 'int32');
        }
        // query params
        if ($predexp !== null) {
            $queryParams['predexp'] = ObjectSerializer::toQueryValue($predexp, null);
        }
        // query params
        if ($read_mode_ap !== null) {
            $queryParams['readModeAP'] = ObjectSerializer::toQueryValue($read_mode_ap, null);
        }
        // query params
        if ($read_mode_sc !== null) {
            $queryParams['readModeSC'] = ObjectSerializer::toQueryValue($read_mode_sc, null);
        }
        // query params
        if (is_array($record_bins)) {
            $record_bins = ObjectSerializer::serializeCollection($record_bins, 'multi', true);
        }
        if ($record_bins !== null) {
            $queryParams['recordBins'] = ObjectSerializer::toQueryValue($record_bins, null);
        }
        // query params
        if ($record_exists_action !== null) {
            $queryParams['recordExistsAction'] = ObjectSerializer::toQueryValue($record_exists_action, null);
        }
        // query params
        if ($replica !== null) {
            $queryParams['replica'] = ObjectSerializer::toQueryValue($replica, null);
        }
        // query params
        if ($respond_all_ops !== null) {
            $queryParams['respondAllOps'] = ObjectSerializer::toQueryValue($respond_all_ops, null);
        }
        // query params
        if ($send_key !== null) {
            $queryParams['sendKey'] = ObjectSerializer::toQueryValue($send_key, null);
        }
        // query params
        if ($sleep_between_retries !== null) {
            $queryParams['sleepBetweenRetries'] = ObjectSerializer::toQueryValue($sleep_between_retries, 'int32');
        }
        // query params
        if ($socket_timeout !== null) {
            $queryParams['socketTimeout'] = ObjectSerializer::toQueryValue($socket_timeout, 'int32');
        }
        // query params
        if ($total_timeout !== null) {
            $queryParams['totalTimeout'] = ObjectSerializer::toQueryValue($total_timeout, 'int32');
        }
        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }

        // path params
        if ($key !== null) {
            $resourcePath = str_replace(
                '{' . 'key' . '}',
                ObjectSerializer::toPathValue($key),
                $resourcePath
            );
        }
        // path params
        if ($namespace !== null) {
            $resourcePath = str_replace(
                '{' . 'namespace' . '}',
                ObjectSerializer::toPathValue($namespace),
                $resourcePath
            );
        }
        // path params
        if ($set !== null) {
            $resourcePath = str_replace(
                '{' . 'set' . '}',
                ObjectSerializer::toPathValue($set),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'application/msgpack']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'application/msgpack'],
                ['application/json', 'application/msgpack']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
