<?php
/**
 * Key
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Aerospike REST Client
 *
 * REST Interface for Aerospike Database.
 *
 * OpenAPI spec version: 1.6.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * Key Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Key implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Key';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'digest' => 'string',
'keytype' => 'string',
'namespace' => 'string',
'set_name' => 'string',
'user_key' => 'object'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'digest' => null,
'keytype' => null,
'namespace' => null,
'set_name' => null,
'user_key' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'digest' => 'digest',
'keytype' => 'keytype',
'namespace' => 'namespace',
'set_name' => 'setName',
'user_key' => 'userKey'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'digest' => 'setDigest',
'keytype' => 'setKeytype',
'namespace' => 'setNamespace',
'set_name' => 'setSetName',
'user_key' => 'setUserKey'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'digest' => 'getDigest',
'keytype' => 'getKeytype',
'namespace' => 'getNamespace',
'set_name' => 'getSetName',
'user_key' => 'getUserKey'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const KEYTYPE_STRING = 'STRING';
const KEYTYPE_INTEGER = 'INTEGER';
const KEYTYPE_BYTES = 'BYTES';
const KEYTYPE_DIGEST = 'DIGEST';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getKeytypeAllowableValues()
    {
        return [
            self::KEYTYPE_STRING,
self::KEYTYPE_INTEGER,
self::KEYTYPE_BYTES,
self::KEYTYPE_DIGEST,        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['digest'] = isset($data['digest']) ? $data['digest'] : null;
        $this->container['keytype'] = isset($data['keytype']) ? $data['keytype'] : null;
        $this->container['namespace'] = isset($data['namespace']) ? $data['namespace'] : null;
        $this->container['set_name'] = isset($data['set_name']) ? $data['set_name'] : null;
        $this->container['user_key'] = isset($data['user_key']) ? $data['user_key'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getKeytypeAllowableValues();
        if (!is_null($this->container['keytype']) && !in_array($this->container['keytype'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'keytype', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['namespace'] === null) {
            $invalidProperties[] = "'namespace' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets digest
     *
     * @return string
     */
    public function getDigest()
    {
        return $this->container['digest'];
    }

    /**
     * Sets digest
     *
     * @param string $digest URL safe base64 encoded key digest. Returned by the server on batch responses. May be provided by client.
     *
     * @return $this
     */
    public function setDigest($digest)
    {
        $this->container['digest'] = $digest;

        return $this;
    }

    /**
     * Gets keytype
     *
     * @return string
     */
    public function getKeytype()
    {
        return $this->container['keytype'];
    }

    /**
     * Sets keytype
     *
     * @param string $keytype Enum describing the type of the userKey. This field is omitted in MessagePack responses.
     *
     * @return $this
     */
    public function setKeytype($keytype)
    {
        $allowedValues = $this->getKeytypeAllowableValues();
        if (!is_null($keytype) && !in_array($keytype, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'keytype', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['keytype'] = $keytype;

        return $this;
    }

    /**
     * Gets namespace
     *
     * @return string
     */
    public function getNamespace()
    {
        return $this->container['namespace'];
    }

    /**
     * Sets namespace
     *
     * @param string $namespace namespace
     *
     * @return $this
     */
    public function setNamespace($namespace)
    {
        $this->container['namespace'] = $namespace;

        return $this;
    }

    /**
     * Gets set_name
     *
     * @return string
     */
    public function getSetName()
    {
        return $this->container['set_name'];
    }

    /**
     * Sets set_name
     *
     * @param string $set_name set_name
     *
     * @return $this
     */
    public function setSetName($set_name)
    {
        $this->container['set_name'] = $set_name;

        return $this;
    }

    /**
     * Gets user_key
     *
     * @return object
     */
    public function getUserKey()
    {
        return $this->container['user_key'];
    }

    /**
     * Sets user_key
     *
     * @param object $user_key The user key, it may be a string, integer, or URL safe Base64 encoded bytes.
     *
     * @return $this
     */
    public function setUserKey($user_key)
    {
        $this->container['user_key'] = $user_key;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
