<?php
/**
 * AdminOperationsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Aerospike REST Client
 *
 * REST Interface for Aerospike Database.
 *
 * OpenAPI spec version: 1.6.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * AdminOperationsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AdminOperationsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for changePassword
     *
     * Change the password of the specified user..
     *
     */
    public function testChangePassword()
    {
    }

    /**
     * Test case for createRole
     *
     * Create a role on the Aerospike cluster..
     *
     */
    public function testCreateRole()
    {
    }

    /**
     * Test case for createUser
     *
     * Create a new user..
     *
     */
    public function testCreateUser()
    {
    }

    /**
     * Test case for dropRole
     *
     * Remove a specific role from the Aerospike cluster..
     *
     */
    public function testDropRole()
    {
    }

    /**
     * Test case for dropUser
     *
     * Remove a user..
     *
     */
    public function testDropUser()
    {
    }

    /**
     * Test case for getRole
     *
     * Get information about a specific role..
     *
     */
    public function testGetRole()
    {
    }

    /**
     * Test case for getRoles
     *
     * Return a list of all roles registered with the Aerospike cluster..
     *
     */
    public function testGetRoles()
    {
    }

    /**
     * Test case for getUser
     *
     * Return information about a specific user..
     *
     */
    public function testGetUser()
    {
    }

    /**
     * Test case for getUsers
     *
     * Return a list of information about users..
     *
     */
    public function testGetUsers()
    {
    }

    /**
     * Test case for grantPrivileges
     *
     * Grant a list of privileges to a specific role..
     *
     */
    public function testGrantPrivileges()
    {
    }

    /**
     * Test case for grantRoles
     *
     * Grant a set of roles to the specified user..
     *
     */
    public function testGrantRoles()
    {
    }

    /**
     * Test case for revokePrivileges
     *
     * Remove a list of privileges from a specific role..
     *
     */
    public function testRevokePrivileges()
    {
    }

    /**
     * Test case for revokeRoles
     *
     * Revoke a set of roles from the specified user..
     *
     */
    public function testRevokeRoles()
    {
    }
}
