<?php
/**
 * KeyValueOperationsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Aerospike REST Client
 *
 * REST Interface for Aerospike Database.
 *
 * OpenAPI spec version: 1.6.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * KeyValueOperationsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class KeyValueOperationsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createRecordNamespaceKey
     *
     * Create a new record with the provided bins into the record..
     *
     */
    public function testCreateRecordNamespaceKey()
    {
    }

    /**
     * Test case for createRecordNamespaceSetKey
     *
     * Create a new record with the provided bins into the record..
     *
     */
    public function testCreateRecordNamespaceSetKey()
    {
    }

    /**
     * Test case for deleteRecordNamespaceKey
     *
     * Delete the specified record..
     *
     */
    public function testDeleteRecordNamespaceKey()
    {
    }

    /**
     * Test case for deleteRecordNamespaceSetKey
     *
     * Delete the specified record..
     *
     */
    public function testDeleteRecordNamespaceSetKey()
    {
    }

    /**
     * Test case for getRecordNamespaceKey
     *
     * Return the metadata and bins for a record..
     *
     */
    public function testGetRecordNamespaceKey()
    {
    }

    /**
     * Test case for getRecordNamespaceSetKey
     *
     * Return the metadata and bins for a record..
     *
     */
    public function testGetRecordNamespaceSetKey()
    {
    }

    /**
     * Test case for recordExistsNamespaceKey
     *
     * Check if a record exists.
     *
     */
    public function testRecordExistsNamespaceKey()
    {
    }

    /**
     * Test case for recordExistsNamespaceSetKey
     *
     * Check if a record exists.
     *
     */
    public function testRecordExistsNamespaceSetKey()
    {
    }

    /**
     * Test case for replaceRecordNamespaceKey
     *
     * Replace the bins of the specified record..
     *
     */
    public function testReplaceRecordNamespaceKey()
    {
    }

    /**
     * Test case for replaceRecordNamespaceSetKey
     *
     * Replace the bins of the specified record..
     *
     */
    public function testReplaceRecordNamespaceSetKey()
    {
    }

    /**
     * Test case for updateRecordNamespaceKey
     *
     * Merge the provided bins into the record..
     *
     */
    public function testUpdateRecordNamespaceKey()
    {
    }

    /**
     * Test case for updateRecordNamespaceSetKey
     *
     * Merge the provided bins into the record..
     *
     */
    public function testUpdateRecordNamespaceSetKey()
    {
    }
}
