<?php
/**
 * SecondaryIndexMethodsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Aerospike REST Client
 *
 * REST Interface for Aerospike Database.
 *
 * OpenAPI spec version: 1.6.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * SecondaryIndexMethodsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SecondaryIndexMethodsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createIndex
     *
     * Create a secondary index..
     *
     */
    public function testCreateIndex()
    {
    }

    /**
     * Test case for dropIndex
     *
     * Remove a secondary Index.
     *
     */
    public function testDropIndex()
    {
    }

    /**
     * Test case for getIndexStats
     *
     * Get Information about a single secondary index..
     *
     */
    public function testGetIndexStats()
    {
    }

    /**
     * Test case for indexInformation
     *
     * Return information about multiple secondary indices..
     *
     */
    public function testIndexInformation()
    {
    }
}
